### ISSUE TITLE
Add another state : "Deallocating"

### ISSUE THREAD

**Issue by dgkanatsios** [PoisonousJohn/AzureGameRoomsScaler#10]
Currently we have two states regarding potential deallocation: "MarkedForDeallocation" and "Deallocated". When the "ReportGameRooms" receives 0 rooms for a VM, then then Azure Deallocate API is called as well as the VM is marked as "Deallocated" in the Storage. 

However, the "Deallocated" VM may be started again in the near future. Since the Deallocation process from Azure ARM API takes some time, what if we introduce a new state "Deallocating" which will transition to "Deallocated" via the relevant event in the Azure Monitor?

We need to avoid having the Azure API call "Start" on a VM which is currently being deallocated. I'm not sure of the result of this operation.

**Comment by PoisonousJohn** [comment]
Agreed. Could you please implement it?
