### ISSUE TITLE
Proposed architecture

### ISSUE THREAD

**Issue by dgkanatsios** [PoisonousJohn/AzureGameRoomsScaler#5]
The application should have a storage mechanism (Table Storage?) to store information about running VMs. This should contain
- VM unique ID (maybe its full ARM ID)
- VM state
- Public IP (if needed)
- whatever else is needed by the game (ports? if available, of course)

VM state should have one of the following values
- Creating
- Running
- MarkedForDeletion

The API Function should have the following operations
- CreateVM. This would check our storage. 
  - If there is at least one VM in the Creating state, the operation should exit. 
  - If there is at least one VM in the MarkedForDeletion state, its state will change to Running and the operation should exit. 
  - Else, this operation should use ARM API to create a new VM. The VM will be marked as Creating state in the storage. When it is created, there will be a mechanism that will update our storage with the new details of the new VM and set its status to Running. (mechanism will probably be Function + Event Grid)
- GetGameRooms(VM_ID). This would ask the VM (via a well-known REST API method) for the current running game rooms/sessions. If there are zero, this operation will call the DeleteVM operation.
- DeleteVM(VM_ID). This will delete the VM via Azure ARM API and the associated line from the storage.
- MarkVMForDeletion(VM_ID): This will mark the VM as MarkedForDeletion in the storage.
- ScheduleGameSession: This method will return a VM that is in the Running state. We should examine if we should somehow get CPU%, RAM% so that we select the VM with the current lowest load.

There should also be another Function that will run on a timed trigger (every 1 minute?) that will enumerate all VMs in the Storage that are MarkedForDeletion. For each one of them, it will call the GetGameRooms operation. If it returns zero, then the Function will call the DeleteVM operation.

**Comment by dgkanatsios** [comment]
Small addition: the DeleteVM method should (????) also delete all other resources associated with VM (IP, VNET etc.)

**Comment by PoisonousJohn** [comment]
Few things to consider:
- DeleteVM should not really delete, only deallocate it. Under the hood I believe we want to have a pool of deallocated VMs that were created in advance, so we will improve the starting time of VMs. Therefore we don't need to delete associated resources.
- ScheduleGameSession I think is out of the scope of this project. I think we will create this mechanics in a different repository (e.g. Azure Game Server monitor). Right now this should be done by the external code. So we keep this project as simple as possible.
- GetGameRooms. How do we get game rooms? I think we should use SetGameRooms, so the external system (e.g. matchmaking) can report how many rooms it has. It also is an advantage, since when this method reports zero game rooms, we can shutdown VM if it was in MarkedForDeletion state (reactive approach is preferrable, instead of polling-based approach).

**Comment by dgkanatsios** [comment]
- So we go for DeallocateVM method, good. Question here is, when we recreate a deallocated VM, what happens with state? We need this reallocated VM to be brand new again, so we somehow reset the state. Or should the game server itself handle this?
- I thought of the Schedule session as a method to query the storage to get an available/running VM (not do the actual schedule for the game). If you think this is not needed, I’m totally good
- I should have called the method ‘GetNumberOfGameRooms’ which will return the number of running game rooms the current VM has. Other than the naming, I think we say the same things. If this method returns zero, the DeallocateVM is called

The reason I thought of the polling Function is for it to work as a means to deallocate VMs that have been requested to deallocate but they still have running game rooms there. Somehow these VMs should be monitored so as to be deallocated when the last game room on them finishes. Unless the matchmaking service will do that, too.

**Comment by PoisonousJohn** [comment]
- Well, we don't have any important state that should be saved between VM launches. So we can consider it as a brand new.
- So Schedule method should be something like GetAvailableVMs (in running state) so external system would be able to query running nodes, if I got your idea right
- Idea is that we actually don't know how to get number of game rooms on the node. This code is really a project-specific. So instead we want **external system** to **report** to us about the game rooms on a specific VM. Then we can react on this. When specific VM reported that game rooms number is zero, we just check the state of VM in our system and decide whether we should deallocate it.

**Comment by dgkanatsios** [comment]
- exactly, method GetAvailableVMs should return details (ID? IP?) about all VMs in the running state
- ah, now I got it. So the polling (or whatever reaction) will be done by the matchmaking service which will then call either Deallocate or CreateNew. 

Great! I'm gonna close this issue and create an architecture.md file on master branch as a starting place to work and finalize the architecture. OK with that?

**Comment by PoisonousJohn** [comment]
@dgkanatsios yeah, sure, thx.
