### ISSUE TITLE
Fill out env variable with the url of FunctionApp

### ISSUE THREAD

**Issue by PoisonousJohn** [PoisonousJohn/AzureGameRoomsScaler#7]
User may want to report GameRooms number directly from VM. One will need an address of a function app for that. It will be used in Minecraft sample as well.

We will utilize custom extension script for that

**Comment by dgkanatsios** [comment]
check out [this](https://github.com/PoisonousJohn/AzureGameRoomsScaler/blob/master/VMmonitorDeploy.json#L152) line, it may be of use for you

**Comment by PoisonousJohn** [comment]
@dgkanatsios reading my mind, huh? Almost dug it my self. Thx mate

**Comment by dgkanatsios** [comment]
Should we close this?

**Comment by PoisonousJohn** [comment]
Yeah, it's done. It's REPORT_ROOMS_URL env variable. It's placed in /etc/profile and /etc/bash.bashrc
