### ISSUE TITLE
Decide on VM naming

### ISSUE THREAD

**Issue by dgkanatsios** [PoisonousJohn/AzureGameRoomsScaler#8]
We need to decide how the VMs will be named. Will it be a unique string coming from the app? Somehow count in user's input?
After that, this need to be enforced in the code, especially in the VMMonitor Function, as we do not want the function to be triggered for VMs created in the subscription for other purposes.

**Comment by PoisonousJohn** [comment]
It's pretty easy. All VMs that we are interested in are created via `CreateNode` method, so we just add them to ourcollection in storage. When VM Monitor reports something, we just look into our list of VMs and proceed only if the VM in our list.

Right now VM names are unique: node[uniqueString(deployment.name())]

**Comment by dgkanatsios** [comment]
As discussed, the VMMonitor Function will *not* handle the "Creating" event but will handle all others ("Created" etc.).
